stages:
  preprocess:
    cmd: python3 preprocess.py --input data/earthquake_alert_balanced_dataset.csv --output data/train_data.csv --output-test data/test_data.csv 
    deps:
      - preprocess.py
      - data/earthquake_alert_balanced_dataset.csv
    outs:
      - data/train_data.csv
      - data/test_data.csv


  train:
    cmd: python3 train.py --train-data data/train_data.csv --model-out nn_model.joblib 
    deps:
      - train.py
      - data/train_data.csv
    outs:
      - nn_model.joblib


  tune:
    cmd: python tune.py --model nn_model.joblib --test-data data/test_data.csv 
    deps:
      - tune.py
      - nn_model.joblib
      - data/test_data.csv