stages:
  preprocess:
    cmd: python preprocess.py --input data/earthquake_alert_balanced_dataset.csv --output data/processed/train_data.csv --output-test data/processed/test_data.csv --output-val data/processed/val_data.csv
    deps:
      - preprocess.py
      - data/earthquake_alert_balanced_dataset.csv
    outs:
      - data/processed/train_data.csv
      - data/processed/test_data.csv
      - data/processed/val_data.csv

  train:
    cmd: python train.py --train-data data/processed/train_data.csv --model-out models/model.pkl 
    deps:
      - train.py
      - data/processed/train_data.csv
    outs:
      - models/model.pkl


  tune:
    cmd: python tune.py --model models/model.pkl --test-data data/processed/test_data.csv 
    deps:
      - tune.py
      - models/model.pkl
      - data/processed/test_data.csv